name: Pass Outputs Between Jobs

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Set Output Value
        id: set_output
        run: |
          echo "::set-output name=my_output::Hello, World!"

  job2:
    needs: job1
    runs-on: ubuntu-latest

    steps:
      - name: Get Input Value
        run: |
          echo "Received input value: ${{ needs.job1.outputs.my_output }}"
