name: Passing Values Between Jobs

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      my_output: ${{ steps.step1.outputs.my_output }}

    steps:
      - name: Step 1
        id: step1
        run: |
          echo "::set-output name=my_output::Hello, World!"

  job2:
    needs: job1
    runs-on: ubuntu-latest

    steps:
      - name: Step 2
        run: |
          echo "Received input value: ${{ needs.job1.outputs.my_output }}"
