name: Build and Deploy

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    outputs:
      version: ${{ steps.read_variables.outputs.stableVersion }}
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2
      

      - name: Read variables
        id: read_variables
        run: |
          stableVersion=$(grep "stableVersion:" .github/variables.yml | awk -F ": " '{print $2}')
          echo "::set-output name=stableVersion::$stableVersion"
      
      - name: Get Tags
        run: git fetch --tags
          
      - name: Compare Tag and Execute build
        run: |
          echo "Comapare tags..."
          CURRENT_TAG="${{ steps.read_variables.outputs.stableVersion }}"
          EXISTING_TAGS=$(git tag --list)
          
          # Compare the current tag with existing tags
          if [[ "${EXISTING_TAGS}" == *"${CURRENT_TAG}"* ]]; then
            echo "The current tag already exists in the main branch."
            
            echo "Blocking PR merge..."
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
            CHECK_NAME="Merge Conditions Check"
            CHECK_TITLE="Merge Conditions Check Failed"
            CHECK_SUMMARY="The pull request does not meet the required merge conditions."
            CHECK_CONCLUSION="failure"
            CHECK_TEXT="Please make sure the PR has the 'allow_merge' label and is targeting the 'main' branch."

            # Create a failure check status using the GitHub Checks API
            curl \
              -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              -d "{
                    \"name\": \"$CHECK_NAME\",
                    \"head_sha\": \"$GITHUB_SHA\",
                    \"status\": \"completed\",
                    \"conclusion\": \"$CHECK_CONCLUSION\",
                    \"output\": {
                      \"title\": \"$CHECK_TITLE\",
                      \"summary\": \"$CHECK_SUMMARY\",
                      \"text\": \"$CHECK_TEXT\"
                    }
                  }" \
              "https://api.github.com/repos/$GITHUB_REPOSITORY/check-runs"
            exit 1
          else
            echo "The current tag is unique and doesn't exist in the main branch."
          fi
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions: write-all
    if: |
      ${{ github.head_ref }} == "main" && ${{ github.base_ref }} == "main" && github.event.pull_request.merged == true
      
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.build.outputs.version }}
          release_name: Release${{ needs.build.outputs.version }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
            - Third Change
          draft: false
          prerelease: false             
        
